osx_image: xcode10.2
language: swift
xcode_workspace: Shuffle.xcworkspace
xcode_scheme: Shuffle
xcode_destination: platform=iOS Simulator,OS=9.0,name=iPhone 6

script:
  - xcodebuild test -workspace Shuffle.xcworkspace -scheme Shuffle -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
